steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-run-de-195-f39da2ac/blue', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/cloud-run-de-195-f39da2ac/blue' ]
logsBucket: 'gs://mylogsbucket'
    options:
      logging: GCS_ONLY
